name: Deploy to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
       
      # Setup .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: 3.1
      # Publishes project
      - name: Publish Project
        run: dotnet publish BoleroDemo.Client/BoleroDemo.Client.fsproj -c Release -o publish --nologo      
        
      # changes the base-tag in index.html from '/' to 'BoleroDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html
        run: sed -i 's;<base href="/">;<base href="/BoleroDemo/"/>;g' publish/wwwroot/index.html
      
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll
      
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{secrets.GITHUBPAGESDEPLOYPRIVATEKEY}}
      
      # Generate GitHub Pages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SSH: true
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: publish/wwwroot
